language: c

sudo: required

services:
  - docker

env:
  global:
    - LUAROCKS=2.2.2
    - DOCKER_COMPOSE_VERSION=1.23.2
  matrix:
    - LUA=lua5.1
    - LUA=luajit2.0  # current head of stable 2.0 branch
    #- LUA=luajit2.1  # current head of unstable 2.1 branch

before_install:
  - sudo apt-get update && sudo apt-get install wget openssl -y
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - cd .travis/docker
  - docker-compose -f create-certs.yml up
  - docker-compose up -d
  - cd ../..
  - source .travis/setenv_lua.sh
  - luarocks install lunitx
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks install luasec 0.7-1

install:
  - luarocks make rockspecs/elasticsearch-lua-1.0.3-1.rockspec

before_script:
  - echo 'elasticsearch version ' && curl http://localhost:9200/
  - curl -XPUT 'localhost:9200/elasticsearch-lua-reindex-index-2'
  - curl -XPUT 'localhost:9200/elasticsearch-lua-reindex-index-1'
  - curl -XPUT 'localhost:9200/elasticsearch-lua-test-index'
  - echo 'Ensure elasticsearch has enough fields configured'
  - "curl -XPUT 'localhost:9200/_settings' -d '{ \"index.mapping.total_fields.limit\": 10000 }' -H 'Content-Type: application/json'"

script:
  - cd tests
  - ./dataset/download-dataset.sh
  - lua run-tests.lua

after_success:  
  - cd ../
  - tests/run-stress-test.sh

notifications:
  email:
    on_success: change
    on_failure: always
