version: '2.2'

services:
  os01:
    image: opensearchproject/opensearch:2.0.0
    container_name: os01
    environment:
      - node.name=os01
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 29200:9200
  
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    environment:
      - node.name=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200

  es02:
    container_name: es02
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    environment:
      - node.name=es02
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=trial
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es02/es02.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es02/es02.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es02/es02.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es02/es02.key
    #volumes: ['esdata_02:/usr/share/elasticsearch/data', './certs:$CERTS_DIR']
    volumes: ['./certs:$CERTS_DIR']
    ports:
      - 19200:9200
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
  
  wait_until_ready:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    command: /usr/bin/true
    depends_on: {"es02": {"condition": "service_healthy"}}

volumes: {"esdata_02": {"driver": "local"}}
